dashboard/urls.py
from django.urls import path
from . import views
from .views import ExportDataView,ExportOrderView
urlpatterns = [ 
    path('dashboard/', views.index, name='dashboard-index'),
    path('staff/', views.staff, name='dashboard-staff'),
    path('staff/detail/<int:pk>/', views.staff_detail, name='dashboard-staff-detail'),
    path('product/', views.product, name='dashboard-product'),
    path('product/delete/<int:pk>/', views.product_delete, name='dashboard-product-delete'),
    path('product/edit/<int:pk>/', views.product_edit, name='dashboard-product-edit'),
    path('order/', views.order, name='dashboard-order'),
    path('order/approve/<int:order_id>/', views.approve_order, name='approve_order'),
    path('order/deny/<int:order_id>/', views.deny_order, name='deny_order'),
    path('order/finish/<int:order_id>/', views.finish_order, name='finish_order'),
    path('order/remove/<int:order_id>/', views.remove_order, name='remove_order'),
    path('order/extend/<int:order_id>/', views.extend_order, name='extend_order'),
    path('order/extend_approve_deny/<int:order_id>/', views.extend_approve_deny, name='extend_approve_deny'),
    path('exportProducts/', ExportDataView.as_view(), name='exportProducts'),
    path('exportOrders/', ExportOrderView.as_view(), name='exportOrders'),
    path('get_products_by_category/', views.get_products_by_category, name='get_products_by_category'),
    path('report_damage/<int:order_id>/', views.report_damage, name='report_damage'),
    path('view_damage_report/<int:order_id>/', views.view_damage_report, name='view_damage_report'),
    path('send-request/', views.send_request, name='send_request'),
    path('view_request/', views.view_request, name='view_request'),
    path('requests/approve/<int:message_id>/',views.approve_request, name='approve_request'),
    path('requests/deny/<int:message_id>/', views.deny_request, name='deny_request'),
    path('requests/remove/<int:message_id>/', views.remove_request, name='remove_request'),
    path('view_request_student/', views.view_request_student, name='view_request_student'),
    path('reserve-studio/', views.reserve_studio, name='reserve_studio'),
    path('approve_reservation/<int:reservation_id>/', views.approve_reservation, name='approve_reservation'),
    path('deny_reservation/<int:reservation_id>/', views.deny_reservation, name='deny_reservation'),
    path('remove_reservation/<int:reservation_id>/', views.remove_reservation, name='remove_reservation'),
    path('remove_request_student/<int:message_id>/', views.remove_request_student, name='remove_request_student'),
    path('remove_reservation_student/<int:reservation_id>/', views.remove_reservation_student, name='remove_reservation_student'),
]

dashboard/models.py
from sre_constants import CATEGORY_DIGIT
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
# Create your models here.
CATEGORY = (
    ('Cables','Cables'),
    ('Lights','Lights'),
    ('Convertors','Convertors'),
    ('Projectors','Projectors'),
    ('Tripod','Tripod'),
    ('Apple','Apple'),
    ('Rec','Rec'),
    ('Camera','Camera'),
    )

class Product(models.Model):
    name = models.CharField(max_length=100,null=True)
    sn = models.CharField(max_length=20, null=True, verbose_name='Serial Number')
    category = models.CharField(max_length=100,choices=CATEGORY,null=True)
    quantity = models.PositiveIntegerField(null=True)

    def __str__(self):
        return f'{self.name}'
    


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True)
    staff = models.ForeignKey(User, models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    returnDate = models.DateTimeField(null=False,default=timezone.now,verbose_name='Return Date')
    status = models.CharField(max_length=10, choices=(('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'),('Finished', 'Finished')), default='Pending')
    extendRequested = models.CharField(max_length=12, choices=(('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'),('NotRequested','NotRequested')), default='NotRequested')
    extendedDate = models.DateTimeField(null=False,default=timezone.now,verbose_name='Extended Date')
    category = models.CharField(max_length=100, choices=CATEGORY, null=True)
    is_reported = models.BooleanField(default=False)


    @property
    def day_before_return(self):
        return self.returnDate - timedelta(days=1)
    def current_date(self):
        return timezone.now().date()
    def __str__(self):
        return f'{self.product.name} - {self.quantity} units'


class DamageReport(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,null=True)
    item = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.item


class Message(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=(('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'),('Finished', 'Finished')), default='Pending')
    is_visible_to_manager = models.BooleanField(default=True)
    is_visible_to_student = models.BooleanField(default=True)


class Reservation(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=(('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'),('Finished', 'Finished')), default='Pending')
    is_visible_to_manager = models.BooleanField(default=True)
    is_visible_to_student = models.BooleanField(default=True)

    def __str__(self):
        return f'Studio Reservation on {self.date}'

dashboard/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required,user_passes_test
from django.http import HttpResponse
from .models import Product,Order,DamageReport,Message,Reservation
from .forms import ProductForm,OrderForm,DamageReportForm,ReservationForm
from .resources import ProductResource,OrderResource
from django.db.models import F
from django.contrib import messages
from django.views import View
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.db.models import Sum
from django.core.exceptions import PermissionDenied
from import_export.formats import base_formats

def staff_required(view_func):
    @login_required(login_url='user_login')
    @user_passes_test(lambda u: u.is_staff, login_url='user_login')
    def wrapper(request, *args, **kwargs):
        return view_func(request, *args, **kwargs)
    return wrapper



# Create your views here.

def reserve_studio(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.customer = request.user
            reservation.save()
            return redirect('dashboard-index')
    else:
        form = ReservationForm()

    return render(request, 'dashboard/reserve_studio.html', {'form': form})

@staff_required
def approve_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    if request.method == 'POST':
        reservation.status = 'Approved'
        reservation.save()
        return redirect('view_request')
    return render(request, 'dashboard/view_request.html', {'reservation': reservation})


@staff_required
def deny_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    if request.method == 'POST':
        reservation.status = 'Denied'
        reservation.save()
        return redirect('view_request')
    return render(request, 'dashboard/view_request.html', {'reservation': reservation})


@staff_required
def remove_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    if request.method == 'POST':
        reservation.is_visible_to_manager = False
        reservation.save()
        return redirect('view_request')
    return render(request, 'dashboard/view_request.html', {'reservation': reservation})


def remove_reservation_student(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    if request.method == 'POST':
        reservation.is_visible_to_student = False
        reservation.save()
        return redirect('view_request_student')
    return render(request, 'dashboard/view_request_student.html', {'reservation': reservation})

def view_request_student(request):
    messages = Message.objects.filter(customer=request.user)  # Filter messages by the current user
    reservations = Reservation.objects.filter(customer=request.user)
    return render(request, 'dashboard/view_request_student.html', {'messages': messages, 'reservations': reservations})

@staff_required
def remove_request(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    if request.method == 'POST':
        message.is_visible_to_manager = False
        message.save()
        return redirect('view_request')
    return render(request, {'message': message})

def remove_request_student(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    if request.method == 'POST':
        message.is_visible_to_student = False
        message.save()
        return redirect('view_request_student')
    return render(request, {'message': message})


@staff_required
def view_request(request):
    if not request.user.is_staff:
        raise PermissionDenied
    messages = Message.objects.all()
    reservations = Reservation.objects.all()

    return render(request, 'dashboard/view_request.html', {'messages': messages, 'reservations': reservations})



def send_request(request):
    products = Product.objects.all()
    
    if request.method == 'POST':
        product_id = request.POST.get('product')
        product = get_object_or_404(Product, pk=product_id)
        message = request.POST.get('message')
        Message.objects.create(
            customer=request.user,
            product=product,
            message=message
        )
        return redirect('dashboard-index')

    return render(request, 'dashboard/send_request.html', {'products': products})


def reserve_request(request):
    products = Product.objects.all()
    
    if request.method == 'POST':
        product_id = request.POST.get('product')
        product = get_object_or_404(Product, pk=product_id)
        message = request.POST.get('message')
        Message.objects.create(
            customer=request.user,
            product=product,
            message=message
        )
        return redirect('dashboard-index')

    return render(request, 'dashboard/reserve_request.html', {'products': products})

@staff_required
def approve_request(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    if request.method == 'POST':
        message.status = 'Approved'
        message.save()
        return redirect('view_request')
    
@staff_required
def deny_request(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    if request.method == 'POST':
        # Perform your denial logic here
        message.status = 'Denied'
        message.save()
        return redirect('view_request')



def report_damage(request, order_id):
    order = Order.objects.get(id=order_id)
    product_name = order.product.name

    if request.method == 'POST':
        form = DamageReportForm(request.POST)
        if form.is_valid():
            damage_report = form.save(commit=False)
            damage_report.order = order
            damage_report.save()
            order.is_reported = True
            order.save()

            return redirect('dashboard-index')
    else:
        form = DamageReportForm(product_name=product_name)

    context = {
        'form': form,
    }
    return render(request, 'dashboard/report_damage.html', context)

@staff_required
def view_damage_report(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    damage_report = DamageReport.objects.get(order=order)
    context = {'order': order, 'damage_report': damage_report}
    return render(request, 'dashboard/view_damage_report.html', context)



def get_products_by_category(request):
    category = request.GET.get('category')
    products = Product.objects.filter(category=category)
    products_data = []
    for product in products:
        product_data = {
            'name': product.name,
            'quantity': product.quantity,
        }
        products_data.append(product_data)

    response_data = {
        'products': products_data,
    }
    return JsonResponse(response_data)


@login_required(login_url='user_login')
def index(request):
    products = Product.objects.filter(quantity__gt=0)
    product_count = Product.objects.aggregate(product_count=Sum('quantity'))['product_count']
    orders = Order.objects.all()
    order_count = orders.count()
    customers = User.objects.exclude(username='admin')
    customer_count = customers.count()

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.staff = request.user
            order.save()
            return redirect('dashboard-index')
    else:
        form = OrderForm()
    context = {
        'form': form,
        'orders': orders,
        'products': products,
        'product_count': product_count,
        'order_count': order_count,
        'customer_count': customer_count,
    }
    return render(request, 'dashboard/index.html', context)

@staff_required
def staff(request):
    products = Product.objects.filter(quantity__gt=0)
    product_count = Product.objects.aggregate(product_count=Sum('quantity'))['product_count']
    orders = Order.objects.all()
    order_count = orders.count()
    customers = User.objects.exclude(username='admin')
    customer_count = customers.count()
    context = {
        'customers':customers,
        'customer_count':customer_count,
        'product_count': product_count,
        'order_count': order_count,
    }
    return render(request,'dashboard/staff.html',context)

@staff_required
def staff_detail(request,pk):
    customers = User.objects.get(id=pk)
    customer_count = User.objects.exclude(username='admin').count()
    products = Product.objects.filter(quantity__gt=0)
    product_count = Product.objects.aggregate(product_count=Sum('quantity'))['product_count']
    orders = Order.objects.all()
    order_count = orders.count()
    context = {
        'customers':customers,
        'customer_count':customer_count,
        'product_count': product_count,
        'order_count': order_count,
    }
    return render(request, 'dashboard/staff_detail.html',context)

@staff_required
def product(request):
    customer_count = User.objects.exclude(username='admin').count()
    products = Product.objects.filter(quantity__gt=0)
    product_count = Product.objects.aggregate(product_count=Sum('quantity'))['product_count']
    orders = Order.objects.all()
    order_count = orders.count()
    items = Product.objects.all()
    unique_categories = set(products.values_list('category', flat=True))
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            product_name = form.cleaned_data.get('name')
            messages.success(request,f'{product_name} has been added!')
            return redirect('dashboard-product')
    else:
        form = ProductForm()
    context = {

templates/dashboard/customer_index.html
<div class="pl-2 pr-2 justify-content-between w-100">
    {% load crispy_forms_tags %}
    <div>
        <div class="row mt-4">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        Make Request
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <!-- {{ form.signature|as_crispy_field }}  Include the signature field -->
                            <input class="btn btn-success" type="submit" value="Make Request">
                        </form>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Orders Records
                    </div>
                    <div class="card-body">
                        <table class="table bg-white">
                            <thead class="bg-info text-white">
                                <tr>
                                    <th scope="col">Product</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in order %}
                                {% if order.customer == user %}
                                <tr>
                                    <td>{{ order.name }}</td>
                                    <td>{{ order.name.category }}</td>
                                    <td>{{ order.order_quantity }}</td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/product.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'partials/topnav.html' %}
<!--Table-->
<div class="pl-2 pr-2 justify-content-between w-100">
    <div class="row my-4">
        <div class="col-md-4">
            {% for message in messages %}
            {% if message %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            <div class="border bg-white p-3">
                <h4>Add Products</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    
                    <input class="btn btn-success btn-block" type="submit" value="Add Product">

                </form>
            </div>
        </div>

        <div class="col-md-8">
            
            
            <div class="table-wrapper">
                            <table id="productTable" class="table bg-white">
              <thead class="bg-primary">
                <tr class="text-white">
                    <th scope="col">
                        <div class="dropdown">
                          <button class="btn btn-link text-white dropdown-toggle" type="button" id="categoryButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            All Categories
                          </button>
                          <div class="dropdown-menu" aria-labelledby="categoryButton">
                            <a class="dropdown-item" href="#" onclick="filterTableByCategory('')">All Categories</a>
                            {% for category in unique_categories %}
                            <a class="dropdown-item" href="#" onclick="filterTableByCategory('{{ category }}')">{{ category }}</a>
                            {% endfor %}
                          </div>
                        </div>
                      </th>
                  <th scope="col"><input type="text" placeholder="Name" id="searchInput">
                  <div class="results"></div></th>
                  <th scope="col">Serial Number</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Activity</th>
                  <th scope="col">
                    <a href="{% url 'exportProducts' %}" class="btn btn-dark btn-sm">Export Products</a>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for item in items %}
                <tr data-category="{{ item.category }}">
                  <td>{{ item.category }}</td>
                  <td class="product" id="{{item.name}}">{{ item.name }}</td>
                  <td>{{ item.sn }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>
                    <a class="btn btn-success btn-sm" href="{% url 'dashboard-product-edit' item.id %}">Edit</a>
                    <a class="btn btn-danger btn-sm" href="{% url 'dashboard-product-delete' item.id %}">Delete</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>

              </div>

          </div>
          
          <script>
            function filterTableByCategory(category) {
                document.getElementById('categoryButton').textContent = category !== '' ? category : 'All Categories';
              if (category === '') {
                $('#productTable tbody tr').show();
              } else {
                $('#productTable tbody tr').hide();
                $('#productTable tbody tr[data-category="' + category + '"]').show();
              }
            }
          </script>
        </div>

    </div>

</div>
<script>
  let productItems = document.querySelectorAll('.product');
  let productNames = [];
  let searchInput = document.querySelector("#searchInput")
  let resultsDiv = document.querySelector(".results");
  let results = []

  for(let i = 0; i < productItems.length; i++) {
    productNames.push(productItems[i].innerHTML);
  }

  searchInput.addEventListener("keyup", function(e) {
    if(e.target.value.length >= 3) {
      console.log(e.target.value);
      resultsDiv.classList.add("show");
      productNames.filter(item => {
        str = item.toLowerCase();
        if(str.match(e.target.value.toLowerCase())) {
          results.push(item);
        }
      })

      if(results) {
      resultsDiv.innerHTML = results.map(item => (`<a href="#${item}">${item}</a>`))
    }
    }
    
    else {
      resultsDiv.classList.remove("show");
      results.splice(0,results.length)
    }
  })

  
</script>

<style>
  #searchInput {
    position:relative;
    background-color: transparent;
    color: #FFF;
    border: 0;
    outline: 0;
  }

  #searchInput::placeholder {
    color: #FFF;
    opacity: 1;
  }

  .results {
    position:absolute;
    top:50px;
    left:0;
    height:300px;
    width:300px;
    z-index: 999;
    overflow-y: auto;
    overflow-x: hidden;
    display: none;
    background-color: #FFF;
    color: black;
    list-style: none;
  }

  .show {
    display: flex !important;
    flex-direction: column;
  }

</style>



<!--End Table-->
{% endblock %}

templates/dashboard/staff_index.html
<div class="container-fluid">
    {% load crispy_forms_tags %}
    <div>
        <div class="row mt-4">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        Make Request
                        
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input class="btn btn-success" type="submit" value="Make Request">
                        </form>
                    </div>
                </div>
                
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-center">
                            <div class="mr-3">
                                <a href="{% url 'reserve_studio' %}" class="btn btn-dark">Reserve Studio</a>
                            </div>
                            <div class="mr-3">
                                <a href="{% url 'send_request' %}" class="btn btn-warning">Out Of Stock Request</a>
                            </div>
                            <div>
                                <a href="{% url 'view_request_student' %}" class="btn btn-info">View Requests</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table bg-white">
                            <thead class="bg-primary text-white">
                                <tr>
                                    <th scope="col">Order #</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Serial Number</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Time Of Order</th>
                                    <th scope="col">Return Date</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Options</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                {% if order.staff == user %}
                                <tr>
                                    <td>{{order.id}}</td>
                                    <td>{{order.product.category}}</td>
                                    <td>{{order.product.name}}</td>
                                    <td>{{order.product.sn}}</td>
                                    <td>{{order.quantity}}</td>
                                    <td>{{order.date|date:"d/m/Y-H:i"}}</td>
                                    
                                    {% if order.current_date|date:"d/m/Y" == order.day_before_return|date:"d/m/Y" and order.status == 'Approved' %}
                                        <td style="color: black">{{ order.returnDate|date:"d/m/Y" }}<br>
                                            <strong>Return Date Approaching!</strong>
                                            
                                        </td>
                                    {% elif order.current_date|date:"d/m/Y" == order.returnDate|date:"d/m/Y" and order.status == 'Approved' %}
                                        <td style="color: red">{{ order.returnDate|date:"d/m/Y" }}<br>
                                            <strong>Today is return day!<br></strong>
                                        </td>
                                    {% else %}
                                    <td>{{ order.returnDate|date:"d/m/Y" }}</td>
                                    {% endif %}

                                    <td>
                                        <span class="
                                        {% if order.status == 'Approved' %}text-success font-weight-bold
                                        {% elif order.status == 'Denied' %}text-danger font-weight-bold
                                        {% elif order.status == 'Finished' %}text-primary font-weight-bold
                                        {% elif order.status == 'Pending' %}text font-weight-bold
                                        {% endif %}">
                                            {{ order.status }}
                                        </span>
                                    </td>
                                    <td>
                                        {% if order.status != 'Pending' %}
                                            {% if not order.is_reported %}
                                                <a class="btn btn-dark btn-sm" href="{% url 'report_damage' order.id %}">Report Damage</a>
                                            {% else %}
                                            <strong>Damage Reported<strong>
                                            {% endif %}
                                            
                                        <br>
                                        {% endif %}
                                        {% if order.current_date|date:"d/m/Y" == order.day_before_return|date:"d/m/Y" and order.status == 'Approved' %}  
                                          <br>
                                          <a class="btn btn-dark btn-sm" href="{% url 'extend_order' order.id %}">Request Extend</a>
                                        {% elif order.current_date|date:"d/m/Y" == order.returnDate|date:"d/m/Y" and order.status == 'Approved' %}
                                          {% if order.extendRequested == 'NotRequested' %}
                                            <br>
                                            <a class="btn btn-dark btn-sm" href="{% url 'extend_order' order.id %}">Request Extend</a>
                                          {% elif order.extendRequested == 'Pending' %}
                                            <br>
                                            <span style="color: black;"><strong>Extend Request Pending<strong></span>
                                          {% elif order.extendRequested == 'Approved' %}
                                            <br>
                                            <span style="color: green;"><strong>Extend Request Has Approved<strong></span>
                                          {% elif order.extendRequested == 'Denied' %}
                                            <br>
                                            <span style="color: red;"><strong>Extend Request Has Denied<strong></span>
                                          {% endif %}
                                        {% endif %}
                                      </td>
                                      
                                    

                                </tr>



                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        var categoryField = $('#id_category');
        var productField = $('#id_product');
        
        categoryField.on('change', function() {
            var selectedCategory = $(this).val();
            
            $.ajax({
                url: '/get_products_by_category/',
                type: 'GET',
                data: { category: selectedCategory },
                success: function(data) {
                    productField.empty();
                    $.each(data, function(key, value) {
                        productField.append($('<option>').text(value).attr('value', key));
                    });
                }
            });
        });
    });
</script>